version: "2"
# https://github.com/sqshq/ELK-docker
services:

#  camel:
#    build: .
#    #image: syscomiddleware/camelfilereader
#    depends_on:
#      - elasticsearch
#    environment:
#      - JVM_OPTS=-Xmx1024m -Xms256m -XX:MaxPermSize=1024m
#    volumes:
#      - ./files:/home/oracle/fileInput

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ports:
      - 19200:9200
      - 9300:9300
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - 5601:5601
    #environment:
    # - ELASTICSEARCH_URL: ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
volumes:
  es-data: